frontend:
  - changed-files:
      - any-glob-to-any-file: 'Frontend/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'Backend/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'release.config.js'
